name: CI

on:
  push:
    tags:
      - 'v'
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/check.yml

  test:
    uses: ./.github/workflows/test.yml

  publish:
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
    needs: [check, test]
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: read
      id-token: write
